### ISSUE TITLE
Two test failures when run as admin user

### ISSUE THREAD

**Issue by djberg96** [djberg96/win32-file-security#1]
Getting two failures when run as admin. I'm not sure if it's just a bad test.

```
Loaded suite C:/ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.3.0/lib/rake/rake_test_loader
Started
.......F
===============================================================================
Failure:
test: group method returns the expected value(TC_Win32_File_Security_Ownership)
c:/Users/djberge/Repositories/win32-file-security/test/test_win32_file_security_ownership.rb:109:in `block in <class:TC_Win32_File_Security_Ownership>'
     106:     else
     107:       expected = @@host + "\\None"
     108:     end
  => 109:     assert_equal(expected, File.group(@@file))
     110:   end
     111: 
     112:   test "group method allows a pathname object" do
<"BUILTIN\\Administrators">(UTF-8) expected but was
<"scipio\\None">(IBM437)

diff:
? BUILTI N\Administrators
? scipio\ o     e        

? Encoding: UTF-8 
?           IBM437
===============================================================================
.F
===============================================================================
Failure:
  <false> expected but was
  <true>
test: grpowned? method returns expected result(TC_Win32_File_Security_Ownership)
c:/Users/djberge/Repositories/win32-file-security/test/test_win32_file_security_ownership.rb:85:in `block in <class:TC_Win32_File_Security_Ownership>'
     82: 
     83:   test "grpowned? method returns expected result" do
     84:     if Win32::Security.elevated_security?
  => 85:       assert_false(File.grpowned?(@@file))
     86:     else
     87:       assert_true(File.grpowned?(@@file))
     88:     end
===============================================================================
........

Finished in 2.495142 seconds.

18 tests, 35 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
88.8889% passed

7.21 tests/s, 14.03 assertions/s
```

**Comment by phasis68** [comment]
The test code for group is invalid.
The group name is always "NONE" for local accounts on non-domain controllers.
Refer to 
https://technet.microsoft.com/en-us/library/cc783557(v=ws.10).aspx

**Comment by djberg96** [comment]
Do you have suggestions for how to ensure the tests pass in either a domain or non-domain environment?

**Comment by phasis68** [comment]
I have no suggestions. Just skipping two failed tests is best option for now.

**Comment by djberg96** [comment]
I decided to add a helper method that calls NetGetDCName. If it fails, then the tests assume it's a local environment. If it looks ok to you I'll keep it. Otherwise I can back it out.

**Comment by djberg96** [comment]
Alright, going to close this out. I think it's fixed. If not, we can revisit it.
